# Generated by Django 6.0.6 on 2026-08-21 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiation')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negotiation_offers',
                'ordering': ['created_at'],
            },
        ),
    ]
