# Generated by Django 6.0.6 on 2026-07-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average traveler rating.', max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rating',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all received ratings.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received by this traveler.'),
        ),
    ]
