# Generated by Django 6.0.6 on 2026-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_average_rating_profile_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancelled_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
