# Generated by Django 6.0.6 on 2026-07-01 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_country', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=100)),
                ('to_country', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reward_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['traveler'], name='trips_travele_89b7ec_idx'), models.Index(fields=['from_city'], name='trips_from_ci_decaae_idx'), models.Index(fields=['to_city'], name='trips_to_city_34305d_idx'), models.Index(fields=['departure_date'], name='trips_departu_03561c_idx'), models.Index(fields=['status'], name='trips_status_b30e85_idx')],
            },
        ),
    ]
