# Generated by Django 6.0.6 on 2026-07-10 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_in_transit_at'),
        ('packages', '0002_package_is_active'),
        ('payment', '0006_stripeeventlog'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payment.bookingpayment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invoices', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.trip')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'), models.Index(fields=['sender'], name='invoices_sender__1039f3_idx'), models.Index(fields=['traveler'], name='invoices_travele_55abfa_idx'), models.Index(fields=['invoice_date'], name='invoices_invoice_e14adb_idx')],
            },
        ),
    ]
