# Generated by Django 6.0.6 on 2026-08-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_generated_at',
        ),
    ]
