# Generated by Django 6.0.6 on 2026-06-30 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('DOCUMENT', 'Document'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('COSMETICS', 'Cosmetics'), ('BOOKS', 'Books'), ('OTHER', 'Other')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=6)),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_amount', models.DecimalField(decimal_places=2, help_text='Amount sender will pay traveler', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pickup_country', models.CharField(max_length=100)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('latest_delivery_date', models.DateField()),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('MATCHED', 'Matched'), ('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package')),
            ],
            options={
                'db_table': 'package_images',
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['sender'], name='packages_sender__f6dd55_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_status_3149ce_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category'], name='packages_categor_75f1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['pickup_country'], name='packages_pickup__965b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['destination_country'], name='packages_destina_15f91c_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['pickup_city'], name='packages_pickup__f1eca5_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['destination_city'], name='packages_destina_2fe973_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['pickup_date'], name='packages_pickup__9dd5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['latest_delivery_date'], name='packages_latest__0e6fd3_idx'),
        ),
    ]
