# Generated by Django 6.0.6 on 2026-07-11 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOCUMENT', 'Document'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('COSMETICS', 'Cosmetics'), ('BOOKS', 'Books'), ('OTHER', 'Other')], max_length=30, unique=True)),
                ('base_risk_score', models.IntegerField(default=0)),
                ('requires_receipt_above', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
            ],
            options={
                'db_table': 'package_risk_rules',
            },
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_categor_75f1cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_pickup__965b2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_destina_15f91c_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_pickup__f1eca5_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_destina_2fe973_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_pickup__9dd5c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='packages_latest__0e6fd3_idx',
        ),
        migrations.AddField(
            model_name='package',
            name='declared_as_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='purchase_receipt',
            field=models.FileField(blank=True, null=True, upload_to='package_receipts/'),
        ),
        migrations.AddField(
            model_name='package',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='traveler_matches_listing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='traveler_refusal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto Approved'), ('VERIFIED', 'Admin Verified'), ('MANUAL_REVIEW', 'Manual Review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['verification_status'], name='packages_verific_454631_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['risk_score'], name='packages_risk_sc_30ca90_idx'),
        ),
    ]
