# Generated by Django 6.0.6 on 2026-08-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_riskrule_remove_package_packages_categor_75f1cc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='declared_value',
        ),
        migrations.RemoveField(
            model_name='package',
            name='reward_amount',
        ),
    ]
