# Generated by Django 6.0.6 on 2026-06-29 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Subscription duration in days.')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial duration in days.')),
                ('badge', models.CharField(blank=True, help_text='Example: Most Popular, Best Value', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Hide plan from frontend without deleting.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Stores plan permissions and limits.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
