# Generated by Django 6.0.6 on 2026-07-01 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0002_package_is_active'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='packages.package')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='trips.trip')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['package'], name='matches_package_98599d_idx'), models.Index(fields=['trip'], name='matches_trip_id_75da2d_idx'), models.Index(fields=['status'], name='matches_status_639056_idx'), models.Index(fields=['score'], name='matches_score_aa87f8_idx'), models.Index(fields=['created_at'], name='matches_created_c34371_idx')],
                'constraints': [models.UniqueConstraint(fields=('package', 'trip'), name='unique_package_trip_match')],
            },
        ),
    ]
