# Generated by Django 6.0.6 on 2026-07-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_withdrawalrequest_wallettransaction_balance_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='bank_account_info',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank Account'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['method'], name='wallets_wit_method_6af155_idx'),
        ),
    ]
