# Generated by Django 6.0.6 on 2026-07-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_remove_withdrawalrequest_bank_account_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket')], default='BANK', max_length=20),
            preserve_default=False,
        ),
    ]
