# Generated by Django 6.0.6 on 2026-07-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_withdrawalrequest_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp confirming absolute banking clearance settlement.', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='stripe_payout_id',
            field=models.CharField(blank=True, help_text='Stripe express destination payout tracking reference (po_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe platform transfer tracking reference (tr_...)', max_length=100, null=True),
        ),
    ]
