# Generated by Django 6.0.6 on 2026-07-15 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_withdrawalmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='wallets_wit_method_6af155_idx',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallets.withdrawalmethod'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='stripe_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['withdrawal_method'], name='wallets_wit_withdra_0874bb_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='wallets_wit_created_195af7_idx'),
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='routing_number',
        ),
    ]
