# Generated by Django 6.0.6 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('TOPUP', 'Wallet Top-up'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('DISPUTE_PAYOUT', 'Dispute Payout'), ('DISPUTE_REFUND', 'Dispute Refund'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_CANCEL', 'Withdrawal Cancel'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
    ]
