# Generated by Django 6.0.6 on 2026-07-08 05:42

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_in_transit_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('DAMAGED_CARGO', 'Items Damaged Upon Delivery'), ('MISSING_ITEMS', 'Items Missing From Shipment'), ('NO_SHOW', 'Traveler Failed to Meet/Deliver'), ('DELAYED_DELIVERY', 'Unacceptable Delivery Delay'), ('OTHER', 'Other Policy Violation')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('REFUND', 'Refund Sender'), ('RELEASE_ESCROW', 'Release Escrow'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_ACTION', 'No Action')], max_length=30)),
                ('description', models.TextField(help_text='Detailed narrative describing the incident.', max_length=2000)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal confidential workspace logs for admins.', max_length=2000)),
                ('disputed_amount', models.DecimalField(decimal_places=2, help_text='The exact escrow funds total frozen under this hold.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_reopened', models.BooleanField(default=False)),
                ('sender_notified', models.BooleanField(default=False)),
                ('traveler_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('against_user', models.ForeignKey(help_text='The user whom the complaint is raised against.', on_delete=django.db.models.deletion.PROTECT, related_name='received_disputes', to=settings.AUTH_USER_MODEL)),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Platform customer manager mediating the case file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(help_text='The transaction under active escrow dispute contention.', on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='bookings.booking')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='Audit tracker of the last user or admin to alter this ticket state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(help_text='The user filing the complaint.', on_delete=django.db.models.deletion.PROTECT, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The specific administrator who executed the final verdict action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Ticket',
                'verbose_name_plural': 'Dispute Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('IMAGE', 'Image Proof'), ('VIDEO', 'Video Recording'), ('DOCUMENT', 'Document Verification')], default='IMAGE', max_length=15)),
                ('file_attachment', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('description', models.CharField(blank=True, help_text='Briefly explain what this proof substantiates.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence Items',
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField(max_length=1500)),
                ('is_admin_note', models.BooleanField(default=False, help_text='Distinguishes platform moderator input text visual styles.')),
                ('is_read', models.BooleanField(default=False, help_text='Tracks active unread badge status flags for counter loops.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Message',
                'verbose_name_plural': 'Dispute Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_di_status_124397_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['created_at'], name='disputes_di_created_ccc858_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['opened_by'], name='disputes_di_opened__4c90b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_admin'], name='disputes_di_assigne_a38871_idx'),
        ),
    ]
