# Generated by Django 6.0.6 on 2026-07-08 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Dispute Case Initialized'), ('ASSIGNED', 'Moderator Assigned'), ('EVIDENCE_ADDED', 'User Evidence Uploaded'), ('EVIDENCE_REQUESTED', 'Information Requested by Admin'), ('RESOLVED_REFUND', 'Case Resolved via Full Refund'), ('RESOLVED_RELEASE', 'Case Resolved via Escrow Release'), ('RESOLVED_PARTIAL', 'Case Resolved via Partial Split'), ('REJECTED', 'Case Dismissed/Rejected'), ('CLOSED', 'Case Permanently Closed')], help_text='System-level action captured in the audit trail.', max_length=50)),
                ('status_from', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], help_text='Previous status before the action.', max_length=30, null=True)),
                ('status_to', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], help_text='New status after the action.', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='disputes.dispute')),
            ],
            options={
                'verbose_name': 'Dispute History Log',
                'verbose_name_plural': 'Dispute History Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_76ae66_idx')],
            },
        ),
    ]
