# Generated by Django 6.0.6 on 2026-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_disputehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('REFUND', 'Refund Sender'), ('RELEASE_ESCROW', 'Release Escrow'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_ACTION', 'No Action')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disputehistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Dispute Case Initialized'), ('ASSIGNED', 'Moderator Assigned'), ('EVIDENCE_ADDED', 'User Evidence Uploaded'), ('EVIDENCE_REQUESTED', 'Information Requested by Admin'), ('RESOLVED_REFUND', 'Resolved - Full Refund'), ('RESOLVED_RELEASE', 'Resolved - Escrow Released'), ('RESOLVED_PARTIAL', 'Resolved - Partial Refund'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], help_text='System-level action captured in the audit trail.', max_length=50),
        ),
    ]
