# Generated by Django 6.0.6 on 2026-07-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_alter_dispute_resolution_alter_disputehistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeevidence',
            name='evidence_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DAMAGE_PHOTO', 'Damage Photo'), ('RECEIPT', 'Receipt'), ('CHAT_LOG', 'Chat Log'), ('OTHER', 'Other')], default='DAMAGE_PHOTO', max_length=15),
        ),
        migrations.AlterField(
            model_name='disputehistory',
            name='action',
            field=models.CharField(choices=[('OPEN', 'Open'), ('OPENED', 'Opened'), ('CREATED', 'Dispute Case Initialized'), ('ASSIGNED', 'Moderator Assigned'), ('EVIDENCE_ADDED', 'User Evidence Uploaded'), ('EVIDENCE_REQUESTED', 'Information Requested by Admin'), ('RESOLVED_REFUND', 'Resolved - Full Refund'), ('RESOLVED_RELEASE', 'Resolved - Escrow Released'), ('RESOLVED_PARTIAL', 'Resolved - Partial Refund'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], help_text='System-level action captured in the audit trail.', max_length=50),
        ),
    ]
