# Generated by Django 6.0.6 on 2026-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_alter_disputeevidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('DAMAGED', 'Items Damaged Upon Delivery'), ('LOST_PACKAGE', 'Lost Package'), ('ITEM_MISSING', 'Missing Items'), ('NO_SHOW', 'Traveler Failed to Meet/Deliver'), ('DELAYED_DELIVERY', 'Unacceptable Delivery Delay'), ('OTHER', 'Other Policy Violation')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('FULL_REFUND', 'Full Refund to Sender'), ('PARTIAL_REFUND', 'Partial Refund'), ('RELEASE_PAYMENT', 'Release Escrow to Traveler'), ('NO_ACTION', 'No Action')], max_length=30, null=True),
        ),
    ]
