# Generated by Django 6.0.6 on 2026-07-14 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0007_pinnedmessage_audio_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('distance_remaining_km', models.FloatField(default=0)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='chat.chatroom')),
                ('tracker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['room'], name='tracking_ac_room_id_b1adf8_idx'), models.Index(fields=['tracker_user'], name='tracking_ac_tracker_12a2dd_idx'), models.Index(fields=['updated_at'], name='tracking_ac_updated_70cddc_idx')],
            },
        ),
    ]
