# Generated by Django 6.0.6 on 2026-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
