# Generated by Django 6.0.6 on 2026-07-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_in_transit_at'),
        ('matching', '0002_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='matching.match'),
        ),
    ]
