# Generated by Django 6.0.6 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed')], default='UNPAID', max_length=20),
        ),
    ]
