# Generated by Django 6.0.6 on 2026-06-27 03:08

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=30)),
                ('id_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('document_front', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kyc/document_front')),
                ('document_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kyc/document_back')),
                ('selfie', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kyc/selfie')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc',
                'ordering': ['-created_at'],
            },
        ),
    ]
