# Generated by Django 6.0.6 on 2026-06-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='date_of_birth',
        ),
    ]
