# Generated by Django 6.0.6 on 2026-06-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_subscription_id',
        ),
    ]
