# Generated by Django 6.0.6 on 2026-07-02 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payment', '0004_remove_payment_stripe_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross transaction amount processed via gateway.', max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission fee deducted from traveler payout.', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO alphabet currency code (e.g., USD, BDT).', max_length=3)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='STRIPE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Initiation'), ('INITIALIZED', 'Gateway Session Created'), ('AUTHORIZED', 'Authorized / Held in Escrow'), ('CAPTURED', 'Captured / Released to Traveler'), ('REFUNDED', 'Refunded to Sender'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, help_text='The checkout/intent session ID generated by the external API provider.', max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, help_text='The active redirection link generated by the gateway for user authentication.', max_length=500, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='The definitive transaction reference indicating finalized settlement.', max_length=255, null=True, unique=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Raw diagnostic logging if status drops to FAILED.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address tracked during checkout initialization for anti-fraud analysis.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(help_text='The single delivery booking instance tied to this escrow transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_payment', to='bookings.booking')),
                ('payee', models.ForeignKey(help_text='The traveler earning the reward payment upon delivery.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_payments_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(help_text='The sender paying for the shipping.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g., payment_intent.succeeded or bKash webhook event', max_length=100)),
                ('raw_payload', models.JSONField(help_text='Raw immutable payload data received directly from the gateway.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='payment.bookingpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['status', 'gateway'], name='payment_boo_status_46804d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['created_at'], name='payment_boo_created_419a5a_idx'),
        ),
    ]
