# Generated by Django 6.0.6 on 2026-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_bookingpayment_bookingpaymentlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(help_text='Full incoming payload string context for historical audit rails.')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Event Log',
                'verbose_name_plural': 'Stripe Event Logs',
            },
        ),
    ]
