# Generated by Django 6.0.6 on 2026-07-26 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Platform fee percentage applied when this payment was created.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual platform fee amount deducted from this payment.', max_digits=12),
        ),
    ]
