# Generated by Django 6.0.6 on 2026-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_bookingpayment_platform_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Initiation'), ('INITIALIZED', 'Gateway Session Created'), ('AUTHORIZED', 'Authorized / Held in Escrow'), ('CAPTURED', 'Captured / Released to Traveler'), ('PARTIAL_REFUND', 'Partially Refunded'), ('REFUNDED', 'Refunded to Sender'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
