# Generated by Django 6.0.6 on 2026-07-06 09:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_in_transit_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating score out of 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional descriptive feedback outlining delivery context behavior.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The verified transactional booking linked to this specific rating execution.', on_delete=django.db.models.deletion.CASCADE, related_name='traveler_review', to='bookings.booking')),
                ('sender', models.ForeignKey(help_text='The cargo owner/sender who is writing the review evaluation.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(help_text='The traveler whose delivery execution performance is being graded.', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review & Rating',
                'verbose_name_plural': 'Reviews & Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='reviews_rev_sender__ae8981_idx'), models.Index(fields=['traveler'], name='reviews_rev_travele_9aaa89_idx'), models.Index(fields=['booking'], name='reviews_rev_booking_3929ad_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'sender'), name='unique_sender_booking_review')],
            },
        ),
    ]
