# Generated by Django 6.0.6 on 2026-08-05 03:29

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_match'),
        ('reviews', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='report_evidence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModerationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_received', models.PositiveIntegerField(default=0, help_text='Total number of reports submitted against this user.')),
                ('valid_reports', models.PositiveIntegerField(default=0, help_text='Number of reports confirmed as valid by an admin.')),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('trust_score', models.PositiveSmallIntegerField(default=100, help_text='Flexible score (0-100) used for ranking and match priority.')),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(choices=[('NONE', 'No Action'), ('WARNING', 'Issue Warning'), ('REMOVE_LISTING', 'Remove Listing / Booking'), ('SUSPEND', 'Suspend Account'), ('PERMANENT_BAN', 'Permanent Ban')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='is_valid',
            field=models.BooleanField(blank=True, help_text='Admin decision on whether this report is genuine/valid.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reviews_rep_status_ce817a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='reviews_rep_reporte_015c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user'], name='reviews_rep_reporte_a238e3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['booking'], name='reviews_rep_booking_c5ac25_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reviews_rep_created_530245_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('reporter', 'reported_user', 'booking'), name='unique_booking_report'),
        ),
        migrations.AddField(
            model_name='reportevidence',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='reviews.report'),
        ),
        migrations.AddField(
            model_name='usermoderationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
