# Generated by Django 6.0.6 on 2026-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_message_id_notification_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MATCH', 'Match'), ('REQUEST', 'Request'), ('BOOKING', 'Booking'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('WALLET', 'Wallet'), ('REVIEW', 'Review'), ('CHAT', 'Chat'), ('REPORT', 'Report'), ('MODERATION', 'Moderation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
    ]
