# Generated by Django 6.0.6 on 2026-08-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MATCH', 'Match'), ('REQUEST', 'Request'), ('BOOKING', 'Booking'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('WALLET', 'Wallet'), ('REVIEW', 'Review'), ('CHAT', 'Chat'), ('REPORT', 'Report'), ('MODERATION', 'Moderation'), ('KYC', 'KYC'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
    ]
