# Generated by Django 6.0.6 on 2026-07-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SYSTEM', 'System')], default='TEXT', max_length=10),
        ),
    ]
