# Generated by Django 6.0.6 on 2026-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_pinnedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedmessage',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds.'),
        ),
    ]
