# Generated by Django 6.0.6 on 2026-08-14 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_status'),
        ('chat', '0007_pinnedmessage_audio_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['traveler', 'sender'], name='chat_chatro_travele_3a0f72_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('sender', 'traveler'), name='unique_sender_traveler_chat_room'),
        ),
    ]
