# Generated by Django 6.0.6 on 2026-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatroom_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Audio duration in seconds'),
        ),
    ]
